import { Metadata } from "next"
import "./styles.css"

export const metadata : Metadata = {
  // NOTE: a title metadata can have these 3 segments:
  title: {
    absolute: 'Smoke weed everyday', // Applied if not blank and if child routes don't have metadata titles i.e setting this on child also overrides layout/parent metadata rules(check "http://localhost:3000/blog/second")
    default: 'Next.js Tutorial - Codevolution', // default is to provide a child route segments with a title that doesn't have it already
    template: '%s | Codevolution', // Merges template literal of title metadata for child route segment as per the rules defined here i.e visiting "http://localhost:3000/blog" will give you
                                   // "Blog | Codevolution" because %s is replaced by "Blog" coming form blog title metadata of blog page/component
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <h1>Hello from header</h1>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <h1>Hello from footer</h1>
        </footer>
      </body>
    </html>
  )
}
